"""empty message

Revision ID: 1eaa52fd66a3
Revises: 
Create Date: 2024-01-29 16:24:57.752181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eaa52fd66a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('user_focus', sa.String(), nullable=True),
    sa.Column('user_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_tickets_assignee_user_id_users')),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_tickets_author_user_id_users')),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_tickets_sprint_id_sprints')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_contributors_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ticket_contributors_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_ticket_logs_author_user_id_users')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_logs_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_logs')
    op.drop_table('ticket_contributors')
    op.drop_table('tickets')
    op.drop_table('users')
    op.drop_table('sprints')
    # ### end Alembic commands ###
